before:
  hooks:
    - go mod tidy
builds:
  - id: spograph
    ldflags:
      - -s -w
    main: main.go
    binary: spograph
    goos:
      - linux
      - windows
      #- darwin
    goarch:
      - amd64
archives:
  - format: zip
